name: Azure Deployment

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@main
      
    - name: 'Login to Azure'
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZ_CRED_DEV }}
