name: Azure Deployment

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@main
      
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CRED_DEV }}
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_DEV }}
        username: ${{ secrets.USER_DEV }}
        password: ${{ secrets.PWD_DEV }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_DEV }}/theapp:latest
        docker push ${{ secrets.REGISTRY_DEV }}/theapp:latest
    
    - name: 'Deploy to ACI'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RG_DEV }}
        dns-name-label: ${{ secrets.RG_DEV }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_DEV }}/theapp:latest
        registry-login-server: ${{ secrets.REGISTRY_DEV }}
        registry-username: ${{ secrets.USER_DEV }}
        registry-password: ${{ secrets.PWD_DEV }}
        name: theapp
        location: 'east us'
        
